package leshy.mushrooms.map.data.local.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import leshy.mushrooms.map.data.local.entity.CategoryEntity
import kotlinx.coroutines.flow.Flow

@Dao
interface CategoryDao {
    @Query("SELECT * FROM categories ORDER BY `order` ASC")
    fun observeAll(): Flow<List<CategoryEntity>>

    @Query("SELECT * FROM categories WHERE isActive = 1 ORDER BY `order` ASC")
    fun observeActive(): Flow<List<CategoryEntity>>

    @Query("SELECT * FROM categories WHERE isFilterEligible = 1 ORDER BY `order` ASC")
    fun observeFilterEligible(): Flow<List<CategoryEntity>>

    /** Species outside the bundled catalog — user-created plus imported ones (i.e. everything the
     * "my mushrooms" section owns). The literal matches `CategorySource.APP.name`, which is what
     * `Converters` stores. Unlike the observers above this one ignores isActive/isPicked: a hidden
     * species must stay listed there, or it could never be brought back. */
    @Query("SELECT * FROM categories WHERE source != 'APP' ORDER BY `order` ASC")
    fun observeNonCatalog(): Flow<List<CategoryEntity>>

    /** One-shot counterpart of [observeAll] — the whole table in a single query, for the catalog
     * seeding diff (408 rows, one read instead of 408 [getByNameKey] lookups). */
    @Query("SELECT * FROM categories ORDER BY `order` ASC")
    suspend fun getAll(): List<CategoryEntity>

    @Query("SELECT * FROM categories WHERE id = :id")
    suspend fun getById(id: Long): CategoryEntity?

    @Query("SELECT * FROM categories WHERE nameKey = :nameKey LIMIT 1")
    suspend fun getByNameKey(nameKey: String): CategoryEntity?

    @Query("SELECT COUNT(*) FROM categories")
    suspend fun count(): Int

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(category: CategoryEntity): Long

    /** Plain INSERT, not REPLACE: these rows are new (`id = 0`, autogenerated) so there is nothing
     * to conflict with, and REPLACE would be a delete+insert that fires `category_collections`'
     * cascade — see `CategoryRepositoryImpl.upsert`'s comment. Room runs the whole list in one
     * transaction. */
    @Insert
    suspend fun insertAll(categories: List<CategoryEntity>)

    @Update
    suspend fun update(category: CategoryEntity)

    @Update
    suspend fun updateAll(categories: List<CategoryEntity>)

    @Delete
    suspend fun delete(category: CategoryEntity)
}
